name: Myget (Pre-Release)

on:
  push:
    branches:   
      - feature/**
jobs:
  build:
    runs-on: windows-latest  
    steps:
      # Checks-out repository
      - uses: actions/checkout@v1
      # Execute psake build script
      - name: Execute psake build with argument (CiPublish2Myget)
        shell: cmd
        run: |
          build.cmd CiPublish2Myget ${{ secrets.MYGET_API_KEY }}
        
        